#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#rm ~/.Xauthority
discord --start-minimized &

if [[ $(xrandr --query | grep -o 'HDMI-1-0 connected') = "HDMI-1-0 connected" ]]; then
~/.screenlayout/all\ 3\ screens.sh
bspc wm -O DP-1-2 HDMI-1-0 eDP-1 
bspc monitor DP-1-2 -d Desktop Console 3 4 5
bspc monitor HDMI-1-0 -d Music Discord 8 9 
bspc monitor eDP-1 -d '^10' 
bspc rule -a discord desktop='^7'
bspc rule -a cider desktop='^6'
else
bspc monitor eDP-1 -d "Browser" School Console Discord Music 6 7 8 9 10
bspc rule -a discord desktop='^3'
bspc rule -a cider desktop='^4'
fi

$HOME/.config/polybar/launch.sh &
picom & 
nitrogen --restore &
rfkill unblock all &
bspc config border_width        4
bspc config window_gap          12

bspc config normal_border_color "#3E3E3C"
bspc config focused_border_color "#774de2"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
