local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>cs', vim.cmd.colorscheme('pywal'), {})
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>cp', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
